### ISSUE TITLE
MVP Milestone

### ISSUE THREAD

**Issue by prestoncabe** [prestoncabe/dmn-benefit-toolbox#28]
We want to have a defined list of what we want to be developed for a "demonstrated vision" / MVP (and what we'll leave for later).  We also want to have an estimated delivery date.

# Proposed MVP Features to build:

* [ ] Basic documentation
    * [ ] README
        * [ ] Scope of the project
        * [ ] How to get started
        * [ ] How it works
        * [ ] Non-goals
    * [ ] How to formulate an input
    * [ ] How to interpret a response
    * [ ] How to create a benefit from existing eligibility checks
        * [ ] Discussion of how eligibility checks combined to check an entire benefit
    * [ ] How to create a new eligibility check
* [ ] Reasonably "complete" library of eligibility checks (incompletely implemented)
    * [ ] Gross Income (make it more general)
    * [ ] Location (make it more general)
    * [x] Age (already general enough BKMs exist... )
    * [ ] Existing enrollments (Make it more general)
    * [ ] (what else?)
* [ ] Demos:
    * [ ] Basic website to allow interaction with a deployed version of the API
        * [ ] Could be as simple as a deployed version of the Swagger UI page?
    * [ ] Homestead vs. LOOP vs. Senior Citizen Tax Freeze calculator
        * [ ] High-level estimate vs. very detailed comparison?
        * [ ] Use Camunda Forms to build?
    * [ ] Example(s) of generators
        * [ ] Eligiblity Check
        * [ ] Benefit
        * [ ] AI (integrate something like Camunda's DMN GPT?)

**Comment by prestoncabe** [comment]
@sierscse I'd like to discuss this more on Tuesday; if you have a chance before we meet please read the outline of proposed features I put on this issue and prepare some thoughts.

One thing I'm thinking already is that it might be ambitious to complete all of the demos, so maybe we should focus on just one for now OR make sure to severely limit how in depth each demo goes?

**Comment by sierscse** [comment]
Some initial thoughts for Tuesday:

- Additional eligibility library check ideas: resources, expense deductions, citizenship, calculating who is part of the benefit household
- There are often one-off eligibility criteria for benefits that are true/false in terms of eligibility. Some examples include: have you bought a new AC in the last 5 years (true = ineligible for NYC Cooling), have you received a 10 year tax abatement on your property (true = ineligible for LOOP), etc. Should there be an 'other' eligibility check?
-  I like the idea that this screener is for more geared towards local programs. There are lots of online SNAP calculators. Many states have screeners for their human services/welfare programs (ex for PA -  https://www.compass.dhs.pa.gov/intake/#/doiqualify/gettingstarted) but local city and municipal programs aren't often part of screening tools. 
- I like the idea of keeping the tools focused on more high-level screenings.

**Comment by prestoncabe** [comment]
Thanks for your thoughts; looking forward to discussing today!

>
>    - Additional eligibility library check ideas: resources, expense
>    deductions, citizenship, calculating who is part of the benefit househould
>
> These all sound like we should add for MVP

>
>    - There are often one-off eligibility criteria for benefits that are
>    true/false in terms of eligibility. Some examples include: have you bought
>    a new AC in the last 5 years (true = ineligible for NYC Cooling), have you
>    received a 10 year tax abatement on your property (true = ineligible for
>    LOOP), etc. Should there be an 'other' eligibility check?
>
> Hmm, I'm not sure about these... part of me wants to say that these kinds
of one-offs should just live in the benefits.dmn, but I think you're right
that they'd be better in something like an "other" dmn.

>
>    - I like the idea that this screener is for more geared towards local
>    programs. There are lots of online SNAP calculators. Many states have
>    screeners for their human services/welfare programs (ex for PA -
>    https://www.compass.dhs.pa.gov/intake/#/doiqualify/gettingstarted) but
>    local city and municipal programs aren't often part of screening tools.
>
> I'm feeling similarly right now; it seems like an unmet need by most of
the code/frameworks/services out there.  I'm imagining a world where
multiple localities can use the same framework to build out logic and
screening tools specific to them with minimal effort.

>
>    - I like the idea of keeping the tools focused on more high-level
>    screenings.
>
> I want to hear more about what you think on this topic; part of me likes
that this would help us focus (and I think it fits with the idea of
focusing on local programs), but I'm also imagining that more programs
screened for would mean more granular information needed (that's my
intuition from experience anyway)... I think the framework we've worked on
so far allows for the full spectrum of high-level to high-detail, so maybe
this issue doesn't need to be a focus?

**Comment by prestoncabe** [comment]
Cycle 1:
- Determine tech stack and deliver prototype of high-level screener.
- Deliver prototype of 1 demo generator
- Deliver public API deployment and Swagger UI website

Cycle 2:
- Write documentation
- Flesh out and complete the screener
- Fix bugs/ rough edges
- Have at least one conversation with someone in City government about including or linking to our tool in city resources.
  - Benephilly Centers?
  - Share on social media?
  - Are any BDT Alumni starting something new in this realm?

**Comment by prestoncabe** [comment]
Going to just close this, since I think MVP has shifted to only be what is necessary to deliver #30 to production.
